# Generated by Django 6.0.2 on 2026-02-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reversed_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_of', to='finance.ledgerentry'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodian_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='users.entity'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='fund_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='finance.fundcluster'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.pettycashfund'),
        ),
        migrations.AddField(
            model_name='responsibilitycenter',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibility_centers', to='users.entity'),
        ),
        migrations.AddField(
            model_name='responsibilitycenter',
            name='fund_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibility_centers', to='finance.fundcluster'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='responsibility_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='finance.responsibilitycenter'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='valid_debit_or_credit'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('fund', 'reference_type', 'reference_no'), name='unique_reference_posting_per_fund'),
        ),
        migrations.AlterUniqueTogether(
            name='responsibilitycenter',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='pettycashfund',
            unique_together={('entity', 'name')},
        ),
    ]
