# Generated by Django 6.0.2 on 2026-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('STATUS_CHANGE', 'Status Change'), ('APPROVAL', 'Approval'), ('RELEASE', 'Release Cash'), ('LIQUIDATION', 'Liquidation'), ('POSTING', 'Ledger Posting'), ('ADJUSTMENT', 'Adjustment'), ('CANCEL', 'Cancel')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
