# Generated by Django 6.0.2 on 2026-02-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('pettycash', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='users.entity'),
        ),
        migrations.AddField(
            model_name='pcvapproval',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.entity'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pettycash.expensecategory'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.pettycashfund'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcvitem',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pettycash.pettycashvoucher'),
        ),
        migrations.AddField(
            model_name='pcvapproval',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pettycash.pettycashvoucher'),
        ),
        migrations.AddField(
            model_name='receiptattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptattachment',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pettycash.pettycashvoucher'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='users.entity'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pettycash.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('entity', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pettycashvoucher',
            unique_together={('entity', 'pcv_no')},
        ),
    ]
