# Generated by Django 6.0.2 on 2026-02-16 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
