# Generated by Django 6.0.2 on 2026-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0003_pettycashvoucher_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='iar_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='pr_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='pcv_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
