# Generated by Django 6.0.2 on 2026-02-19 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0006_pettycashvoucher_release_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('action', models.CharField(choices=[('RETURNED', 'Returned to Staff'), ('APPROVED', 'Approved by Custodian')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation_reviews', to='pettycash.pettycashvoucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
