# Generated by Django 6.0.2 on 2026-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0007_liquidationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='is_liquidation_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='is_release_posted',
            field=models.BooleanField(default=False),
        ),
    ]
