# Generated by Django 6.0.2 on 2026-02-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('pettycash', '0008_pettycashvoucher_is_liquidation_posted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('series_number', models.IntegerField()),
                ('report_number', models.CharField(max_length=20, unique=True)),
                ('check_number', models.CharField(max_length=50)),
                ('check_date', models.DateField()),
                ('check_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.pettycashfund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='replenishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='pettycash.replenishment'),
        ),
    ]
