# Generated by Django 6.0.2 on 2026-02-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0009_replenishment_pettycashvoucher_replenishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='is_replenished',
            field=models.BooleanField(default=False),
        ),
    ]
