# Generated by Django 6.0.2 on 2026-02-21 05:52

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('pettycash', '0010_pettycashvoucher_is_replenished'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pettycashvoucher',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='amount_liquidated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='pettycashvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('pcv_no__isnull', False)), fields=('entity', 'pcv_no'), name='unique_pcv_no_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='pettycashvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('is_replenished', False), ('replenishment__isnull', False), _connector='OR'), name='replenished_must_have_replenishment'),
        ),
        migrations.AddConstraint(
            model_name='pettycashvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('is_replenished', False), ('status', 'POSTED'), _connector='OR'), name='replenished_must_be_posted'),
        ),
        migrations.AddConstraint(
            model_name='pettycashvoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_posted_to_ledger', True), ('status', 'POSTED')), models.Q(('status', 'POSTED'), _negated=True), _connector='OR'), name='posted_status_requires_flag'),
        ),
    ]
