# Generated by Django 6.0.2 on 2026-02-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('pettycash', '0011_alter_pettycashvoucher_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='sheet_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Report Generated)'), ('SUBMITTED', 'Submitted to Accounting'), ('APPROVED', 'Approved for Payment'), ('RELEASED', 'Check Released to Custodian'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='check_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='check_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishments', to='finance.pettycashfund'),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='report_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='replenishment',
            unique_together={('fund', 'year', 'series_number')},
        ),
    ]
