# Generated by Django 6.0.2 on 2026-02-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0012_replenishment_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_ACCOUNTING', 'Submitted to Accounting'), ('RELEASED', 'Released')], default='DRAFT', max_length=30),
        ),
    ]
