# Generated by Django 6.0.2 on 2026-02-25 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('pettycash', '0013_alter_replenishment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='cash_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='replenishment',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='replenishment',
            constraint=models.CheckConstraint(condition=models.Q(('cash_on_hand__gte', 0)), name='cash_on_hand_non_negative'),
        ),
    ]
