# Generated by Django 6.0.2 on 2026-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash', '0014_replenishment_cash_on_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='has_cnrr',
            field=models.BooleanField(default=False),
        ),
    ]
